#format = '$all'

# Which is equivalent to
#format = """
#$username\
#$hostname\
#$localip\
#$shlvl\
#$singularity\
#$kubernetes\
#$directory\
#$vcsh\
#$fossil_branch\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$hg_branch\
#$pijul_channel\
#$docker_context\
#$package\
#$c\
#$cmake\
#$cobol\
#$daml\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$fennel\
#$golang\
#$guix_shell\
#$haskell\
#$haxe\
#$helm\
#$java\
#$julia\
#$kotlin\
#$gradle\
#$lua\
#$nim\
#$nodejs\
#$ocaml\
#$opa\
#$perl\
#$php\
#$pulumi\
#$purescript\
#$python\
#$raku\
#$rlang\
#$red\
#$ruby\
#$rust\
#$scala\
#$solidity\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$buf\
#$nix_shell\
#$conda\
#$meson\
#$spack\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$azure\
#$env_var\
#$crystal\
#$custom\
#$sudo\
#$cmd_duration\
#$line_break\
#$jobs\
#$battery\
#$time\
#$status\
#$os\
#$container\
#$shell\
#$character"""

#format = """
#[â–‘â–’â–“](#a3aed2)\
#[ îœ‘ ](bg:#a3aed2 fg:#090c0c)\
#[î‚´](bg:#769ff0 fg:#a3aed2)\
#$directory\
#[î‚´](fg:#769ff0 bg:#394260)\
#$git_branch\
#$git_status\
#[î‚´](fg:#394260 bg:#212736)\
#$nodejs\
#$rust\
#$golang\
#$php\
#[î‚´](fg:#212736 bg:#1d2230)\
#$time\
#[î‚´ ](fg:#1d2230)\
#\n$character"""

continuation_prompt = 'â–¶â–¶ '

format = """
[\ue0b6](fg:#212736)\
[$time](fg:#212736 bg:#1d2230)\
\ue0b2\
$os\
[\ue0b2](bg:#e4e4e4 fg:#073278)\
[ $username @ $hostname ](bg:#073278 fg:#e4e4e4)\
[\ue0b0](bg:#3465a4 fg:#073278)\
$directory\
[\ue0b0](bg:#073278 fg:#3465a4)\
$shell\
[\ue0b0](bg:#4e9a06 fg:#073278)\
$git_branch\
$git_status\
[\ue0b0](bg:#212736 fg:#4e9a06)\
[\ue0b0](bg:#212736 fg:#394260)\
$nodejs\
$rust\
$golang\
$php\
[\ue0b0](bg:#1d2230 fg:#212736)\
$status\
$cmd_duration\
[\ue0b4 ](fg:#1d2230)
$character"""

[cmd_duration]
format = "[:](bg:#1d2230 fg:#212736)[ $duration ]($style)"
min_time = 200
show_milliseconds = true
style = "fg:#9b9b9b bg:#1d2230"

[directory]
style = "bg:#3465a4 fg:#e4e4e4"
format = "[ ï¼ $path ]($style)"
truncate_to_repo = false
truncation_length = 0
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#4e9a06 fg:#000000"
format = '[[ $symbol $branch(:$remote_branch) ](bg:#4e9a06 fg:#000000)]($style)'

[git_status]
style = "bg:#4e9a06 fg:#000000"
format = '[[($all_status$ahead_behind )](bg:#4e9a06 fg:#000000)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false
style = 'bg:#073278 fg:#e4e4e4'

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[os]
disabled = false
#format = '[ $symbol$name ]($style)''
format = '[ $symbol ]($style)'
style = "bg:#d3d7cf fg:#000000"

# This is the default symbols table.
[os.symbols]
#Alpaquita = "ğŸ”” "
Alpine = "ïŒ€ "          # \uF300
#Amazon = "ğŸ™‚ "
#Android = "ğŸ¤– "
Arch = "ïŒƒ "            # \uF303
#Artix = "ğŸ—ï¸ "
CentOS = "ïŒ„ "          # \uF304
Debian = "ïŒ† "          # \uF306
#DragonFly = "ğŸ‰ "
#Emscripten = "ğŸ”— "
EndeavourOS = "ïŒ¢ "     # \uF322
Fedora = "ïŒŠ "          # \uF30A
FreeBSD = "ïŒŒ "         # \uF30C
#Garuda = "ğŸ¦… "
Gentoo = "ïŒ "          # \uF30D
#HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ïŒ¦ "         # \uF326
Linux = "ï…¼ "           # \uF17C
#Mabox = "ğŸ“¦ "
Macos = "ï…¹ "           # \uF179
Manjaro = "ïŒ’ "         # \uF312
#Mariner = "ğŸŒŠ "
#MidnightBSD = "ğŸŒ˜ "
Mint = "ïŒ "            # \uF30E
#NetBSD = "ğŸš© "
NixOS = "ïŒ“ "           # \uF313
OpenBSD = "ïŒ¨ "         # \uF328
#OpenCloudOS = "â˜ï¸ "
#openEuler = "ğŸ¦‰ "
openSUSE = "ïŒ” "        # \uF314
#OracleLinux = "ğŸ¦´ "
Pop = "ïŒª "             # \uF32A
Raspbian = "ïŒ• "        # \uF315
Redhat = "ïŒ– "          # \uF316
RedHatEnterprise = " " # \uF316
#Redox = "ğŸ§ª "
#Solus = "â›µ "
SUSE = "ïŒ” "            # \uF314
Ubuntu = "ïŒ› "          # \uF31B
Unknown = "? "
Windows = "î˜ª "         # \uE62A

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[shell]
bash_indicator = 'ï…•'
#cmd_indicator = ''
disabled = false
format = '[ $indicator ]($style)'
powershell_indicator = 'î¢'
style = "bg:#073278 fg:#e4e4e4"

[status]
disabled = false
format = "[ $signal_name $symbol ]($style)"
map_symbol = true
sigint_symbol = "[âœ—](bg:#1d2230 fg:#d60202)"
style = "bg:#1d2230"
success_symbol = "[âœ“](bg:#1d2230 fg:green)"
symbol = "[âœ—](bg:#1d2230 fg:#d60202)"

[time]
disabled = false
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
style = "bg:#1d2230"
time_format = "%T ïº %d-%b-%Y"

[username]
disabled = false
format = '[$user]($style)'
show_always = true
style_root = "bg:#073278 fg:#ffff66"
style_user = "bg:#073278 fg:#e4e4e4"
